### PR TITLE
Use actively developed YAML-to-JSON library

### PR DESCRIPTION
**Pull request by joelochlann**
Was unable to run `npm run cloudformation --loglevel silent > cloudformation.json` as per documentation.

This is because the [npm package `yaml-to-json`](https://github.com/debrouwere/yaml2json) depends on asciidoctor.js whose [latest release version](https://github.com/asciidoctor/asciidoctor.js/issues/172) is broken. The problem is fixed, but on a release candidate version, which means yaml-to-json's [semver dependency](https://github.com/debrouwere/yaml2json/blob/master/package.json#L22) will not pick it up.

Rather than wait for either asciidoctor to release the fix as a minor version or yaml-to-json to change the version of their dependency on asciidoctor, I decided to use a different library, especiialy since yaml-to-json only ever had one contributor and its last commit was two years ago. [`yaml-js`](https://github.com/jeremyfa/yaml.js) has 14 contributors and many more [downloads & stars](https://www.npmjs.com/package/yamljs) so for the time being it seems like a better choice.

To get it to work though I had to tighten up our YAML syntax a bit.

@dominickendrick @katebee

### CODE REVIEW

**Comment by joelochlann** [comment]
@janua

**Comment by janua** [comment]
:+1:

**Comment by joelochlann** [comment]
Travis build failing because of npm issues - locally, upgrading the npm version and a bunch of the dev dependencies solves the problem, so I've pushed up these changes and will see if I can get the Travis build to pass

**Comment by joelochlann** [comment]
Another build issue now - looks like our keys for uploading the artifact to s3 may be out of date. Waiting til I can ask @sihil or @philwills for the latest keys

**Comment by sihil** [comment]
The keys should be specific to the frontend AWS account. We delegate access to the bucket to each account and then let individual accounts create their own IAM users to put in Travis / Circle. Happy to chat further and help you troubleshoot though.

**Comment by sihil** [comment]
I presume that now AWS have native YAML support this PR can be killed @joelochlann ?

**Pull request closed without merging**
